name: PSP

on:
  push:
    branches:
      - psp
    paths-ignore:
      - '*.md'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
  release:
    types: [published]
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  psp:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install -y cmake curl g++ git lcov libgtest-dev libgmock-dev libfmt-dev libsdl2-dev libsodium-dev libpng-dev libbz2-dev wget gettext

    - name: Setup PSPTOOLCHAIN
      # You may pin to the exact commit or the version.
      # uses: krystalgamer/setup-psptoolchain@9042bd00c5813d383183c3967aef4f66713a4974
      uses: krystalgamer/setup-psptoolchain@latest
  
    - name: Cache CMake build folder
      uses: actions/cache@v2
      with:
        path: build
        key: psp-cmake-v5-${{ github.sha }}
        restore-keys: psp-cmake-v5-

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=OFF -DCPACK=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_TOOLCHAIN_FILE=../CMake/platforms/psp_defs.cmake

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        psp-cmake -S. -Bbuild  -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_PRX=1 -DENC_PRX=1
        cmake --build build -j $(nproc)
  
    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: EBOOT.PBP
        path: EBOOT.PBP
