name: PSP

on:
  push:
    branches:
      - psp
    paths-ignore:
      - '*.md'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
  release:
    types: [published]
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  psp:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup PSPTOOLCHAIN
      # You may pin to the exact commit or the version.
      # uses: krystalgamer/setup-psptoolchain@9042bd00c5813d383183c3967aef4f66713a4974
      uses: krystalgamer/setup-psptoolchain@latest
  
    - name: Run BUILD
      run: >
        psp-cmake -S. -Bbuild  -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_PRX=1 -DENC_PRX=1
        cmake --build build -j 2
  
    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v2
      with:
        name: EBOOT.PBP
        path: ./EBOOT.PBP
